#!/usr/bin/env node
// Build-time generator for MCP App widget HTML.
//
// Authored HTML lives under src/ui/widgets/src/*.html.
// This script wraps each file's contents in a TypeScript module that exports
// the HTML as a string constant. The output lands under
// src/ui/widgets/generated/ which is gitignored and recreated on every build.
//
// We use this indirection because tsconfig.json only compiles src/**/*.ts —
// raw HTML assets would not be copied into dist/ by `tsc`. Embedding the HTML
// as a TypeScript string literal keeps the build pipeline dependency-free and
// guarantees the widget HTML is always present in the compiled output.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from "node:fs";
import { resolve, dirname, basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..");
const srcDir = resolve(repoRoot, "src", "ui", "widgets", "src");
const outDir = resolve(repoRoot, "src", "ui", "widgets", "generated");
const bridgeEntry = resolve(repoRoot, "src", "ui", "widgets", "bridge", "host-bridge.ts");

if (!existsSync(srcDir)) {
  console.error(`[build-widgets] source directory missing: ${srcDir}`);
  process.exit(1);
}

// Bundle the MCP Apps host bridge (@modelcontextprotocol/ext-apps `App` + the
// postMessage transport that performs the `ui/initialize` handshake) into a
// single self-contained IIFE. It is inlined into every widget HTML so the
// widgets are dependency-free at runtime inside the sandboxed iframe.
async function bundleBridge() {
  const result = await build({
    entryPoints: [bridgeEntry],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: ["es2019"],
    minify: true,
    legalComments: "none"
  });
  const text = result.outputFiles?.[0]?.text;
  if (!text) {
    throw new Error("[build-widgets] esbuild produced no bridge output");
  }
  return text;
}

const bridgeIife = await bundleBridge();
const bridgeScriptTag = `<script>${bridgeIife}</script>`;
const BRIDGE_MARKER = "<!-- MCP_HOST_BRIDGE -->";
console.log(`[build-widgets] bundled MCP Apps host bridge (${bridgeIife.length} bytes)`);

function injectBridge(html, file) {
  // IMPORTANT: use a replacement FUNCTION, never a replacement string. The
  // bundle is ~450 KB and contains `$\`` (dollar-backtick), `$'`, `$$` and `$&`
  // sequences. String.prototype.replace interprets those in a replacement
  // string (e.g. `$\`` injects the text before the match), which silently
  // corrupts the bundle. A function replacement returns the value verbatim.
  const insert = () => bridgeScriptTag;
  if (html.includes(BRIDGE_MARKER)) {
    return html.replace(BRIDGE_MARKER, insert);
  }
  if (html.includes("</head>")) {
    console.warn(`[build-widgets] ${file}: no ${BRIDGE_MARKER} marker, injecting before </head>`);
    return html.replace("</head>", () => `${bridgeScriptTag}\n</head>`);
  }
  console.warn(`[build-widgets] ${file}: no marker and no </head>, prepending bridge`);
  return bridgeScriptTag + html;
}

// Wipe and recreate the generated/ folder so stale entries can't leak in.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

function toConstName(fileName) {
  return fileName
    .replace(/\.html$/i, "")
    .replace(/[-.]/g, "_")
    .toUpperCase() + "_HTML";
}

// The widget HTML inlines a large (~450 KB) esbuild bundle that is full of
// backticks and `${...}` template literals. Embedding that inside a JS template
// literal (and escaping it) corrupts the bundle. We therefore store the HTML as
// base64 — which contains only [A-Za-z0-9+/=], so no character can break out of
// the string literal or close the inline <script> tag.
function toBase64Module(constName, file, html) {
  const b64 = Buffer.from(html, "utf8").toString("base64");
  return `// Auto-generated by scripts/dev/build-widgets.mjs — do not edit.
// Source: src/ui/widgets/src/${file}
/* eslint-disable */
export const ${constName} = Buffer.from(
  "${b64}",
  "base64"
).toString("utf8");
`;
}

const htmlFiles = readdirSync(srcDir).filter(f => f.toLowerCase().endsWith(".html")).sort();

if (htmlFiles.length === 0) {
  console.error(`[build-widgets] no .html files found under ${srcDir}`);
  process.exit(1);
}

const indexExports = [];

for (const file of htmlFiles) {
  const rawHtml = readFileSync(join(srcDir, file), "utf8");
  const html = injectBridge(rawHtml, file);
  const constName = toConstName(file);
  const tsModule = toBase64Module(constName, file, html);
  const outFile = file.replace(/\.html$/i, ".ts");
  writeFileSync(join(outDir, outFile), tsModule, "utf8");
  indexExports.push(`export { ${constName} } from "./${basename(outFile, ".ts")}";`);
  console.log(`[build-widgets] generated ${outFile} (${html.length} bytes)`);
}

// Barrel re-export so widgets.ts only needs a single import.
writeFileSync(
  join(outDir, "index.ts"),
  `// Auto-generated by scripts/dev/build-widgets.mjs — do not edit.\n` +
    `/* eslint-disable */\n` +
    indexExports.join("\n") +
    "\n",
  "utf8"
);

console.log(`[build-widgets] wrote ${htmlFiles.length} widget module(s) to ${outDir}`);
